// Code generated by gtrace. DO NOT EDIT.

package test

// Compose returns a new InnerTrace which has functional fields composed
// both from t and x.
func (t InnerTrace) Compose(x InnerTrace) (ret InnerTrace) {
	switch {
	case t.OnInner == nil:
		ret.OnInner = x.OnInner
	case x.OnInner == nil:
		ret.OnInner = t.OnInner
	default:
		h1 := t.OnInner
		h2 := x.OnInner
		ret.OnInner = func() {
			h1()
			h2()
		}
	}
	return ret
}
func (t InnerTrace) onInner() {
	fn := t.OnInner
	if fn == nil {
		return
	}
	fn()
}
