// Code generated by gtrace. DO NOT EDIT.

package test

import (
	"github.com/gobwas/gtrace/test/internal"
)

// Compose returns a new TraceComposite which has functional fields composed
// both from t and x.
func (t TraceComposite) Compose(x TraceComposite) (ret TraceComposite) {
	switch {
	case t.OnPointer == nil:
		ret.OnPointer = x.OnPointer
	case x.OnPointer == nil:
		ret.OnPointer = t.OnPointer
	default:
		h1 := t.OnPointer
		h2 := x.OnPointer
		ret.OnPointer = func(t *internal.Type) {
			h1(t)
			h2(t)
		}
	}
	switch {
	case t.OnSlice == nil:
		ret.OnSlice = x.OnSlice
	case x.OnSlice == nil:
		ret.OnSlice = t.OnSlice
	default:
		h1 := t.OnSlice
		h2 := x.OnSlice
		ret.OnSlice = func(t []internal.Type) {
			h1(t)
			h2(t)
		}
	}
	switch {
	case t.OnArray == nil:
		ret.OnArray = x.OnArray
	case x.OnArray == nil:
		ret.OnArray = t.OnArray
	default:
		h1 := t.OnArray
		h2 := x.OnArray
		ret.OnArray = func(t [2]internal.Type) {
			h1(t)
			h2(t)
		}
	}
	switch {
	case t.OnChan == nil:
		ret.OnChan = x.OnChan
	case x.OnChan == nil:
		ret.OnChan = t.OnChan
	default:
		h1 := t.OnChan
		h2 := x.OnChan
		ret.OnChan = func(t chan internal.Type) {
			h1(t)
			h2(t)
		}
	}
	switch {
	case t.OnMap == nil:
		ret.OnMap = x.OnMap
	case x.OnMap == nil:
		ret.OnMap = t.OnMap
	default:
		h1 := t.OnMap
		h2 := x.OnMap
		ret.OnMap = func(t map[string]internal.Type) {
			h1(t)
			h2(t)
		}
	}
	switch {
	case t.OnMapKey == nil:
		ret.OnMapKey = x.OnMapKey
	case x.OnMapKey == nil:
		ret.OnMapKey = t.OnMapKey
	default:
		h1 := t.OnMapKey
		h2 := x.OnMapKey
		ret.OnMapKey = func(t map[internal.Type]string) {
			h1(t)
			h2(t)
		}
	}
	switch {
	case t.OnNested == nil:
		ret.OnNested = x.OnNested
	case x.OnNested == nil:
		ret.OnNested = t.OnNested
	default:
		h1 := t.OnNested
		h2 := x.OnNested
		ret.OnNested = func(t []map[internal.Type]*[]internal.Type) {
			h1(t)
			h2(t)
		}
	}
	return ret
}
func (t TraceComposite) onPointer(t1 *internal.Type) {
	fn := t.OnPointer
	if fn == nil {
		return
	}
	fn(t1)
}
func (t TraceComposite) onSlice(t1 []internal.Type) {
	fn := t.OnSlice
	if fn == nil {
		return
	}
	fn(t1)
}
func (t TraceComposite) onArray(t1 [2]internal.Type) {
	fn := t.OnArray
	if fn == nil {
		return
	}
	fn(t1)
}
func (t TraceComposite) onChan(t1 chan internal.Type) {
	fn := t.OnChan
	if fn == nil {
		return
	}
	fn(t1)
}
func (t TraceComposite) onMap(t1 map[string]internal.Type) {
	fn := t.OnMap
	if fn == nil {
		return
	}
	fn(t1)
}
func (t TraceComposite) onMapKey(t1 map[internal.Type]string) {
	fn := t.OnMapKey
	if fn == nil {
		return
	}
	fn(t1)
}
func (t TraceComposite) onNested(t1 []map[internal.Type]*[]internal.Type) {
	fn := t.OnNested
	if fn == nil {
		return
	}
	fn(t1)
}
func traceCompositeOnPointer(t TraceComposite, t1 *internal.Type) {
	t.onPointer(t1)
}
func traceCompositeOnSlice(t TraceComposite, t1 []internal.Type) {
	t.onSlice(t1)
}
func traceCompositeOnArray(t TraceComposite, t1 [2]internal.Type) {
	t.onArray(t1)
}
func traceCompositeOnChan(t TraceComposite, t1 chan internal.Type) {
	t.onChan(t1)
}
func traceCompositeOnMap(t TraceComposite, t1 map[string]internal.Type) {
	t.onMap(t1)
}
func traceCompositeOnMapKey(t TraceComposite, t1 map[internal.Type]string) {
	t.onMapKey(t1)
}
func traceCompositeOnNested(t TraceComposite, t1 []map[internal.Type]*[]internal.Type) {
	t.onNested(t1)
}
