// Code generated by gtrace. DO NOT EDIT.

package test

// Compose returns a new OuterTrace which has functional fields composed
// both from t and x.
func (t OuterTrace) Compose(x OuterTrace) (ret OuterTrace) {
	ret.Inner = t.Inner.Compose(x.Inner)
	switch {
	case t.OnOuter == nil:
		ret.OnOuter = x.OnOuter
	case x.OnOuter == nil:
		ret.OnOuter = t.OnOuter
	default:
		h1 := t.OnOuter
		h2 := x.OnOuter
		ret.OnOuter = func() {
			h1()
			h2()
		}
	}
	return ret
}
func (t OuterTrace) onOuter() {
	fn := t.OnOuter
	if fn == nil {
		return
	}
	fn()
}
